name: Update Major Tag

on:
  release:
    types: [published]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for the action to push tags back to the repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Must fetch all history to work with tags properly

      - name: Update Major Tag
        uses: artryazanov/update-major-tag-action@v1
